config/routes.rb
Rails.application.routes.draw do
  get 'top_referrers' => 'stats#top_referrers'
  get 'top_urls' => 'stats#top_urls'

  root to: 'stats#index'
end

app/models/entry.rb
class Entry < Sequel::Model
  plugin :validation_helpers
  plugin :timestamps, create: :created_at

  dataset_module do
    def last_five_days
      where(Sequel.function(:date, :created_at) => (Date.today - 5.days..Date.today))
    end
  end

  def validate
    super
    validates_presence [:url, :created_at]
  end

  def before_save
    super

    self.entry_hash = generate_entry_hash
  end

  def top_referrers
    attributes_to_select = [:referrer]
    Entry.last_five_days.where(
      url: url
    ).exclude(
      referrer: nil
    ).select(
      *attributes_to_select
    ).group_and_count(
      *attributes_to_select
    ).order(:count).reverse
  end

  def self.top_entries
    attributes_to_select = [:url, Sequel.as(Sequel.function(:date, :created_at), :date)]
    Entry.last_five_days.select(
      *attributes_to_select
    ).group_and_count(
      *attributes_to_select
    ).order(:count).reverse
  end

  private

  def generate_entry_hash
    Digest::MD5.hexdigest(
      values.slice(:id, :url, :referrer, :created_at).to_s
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
  end

  def top_urls
    respond_to do |format|
      format.html
      format.json do
        top_entries
      end
    end
  end

  def top_referrers
    respond_to do |format|
      format.html
      format.json do
        top_entries
      end
    end
  end

  private

  def top_entries
    @result = Entry.top_entries.inject({}) do |hash, item|
      hash[item[:date].to_s] ||= []
      hash[item[:date].to_s] << item
      hash
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnalyticsDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
  <script src="all.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stats/index.html.erb
<%= link_to "Top URLS", top_urls_path %> |
<%= link_to "Top Referrers", top_referrers_path %>

app/views/stats/top_referrers.html.erb
<%= link_to "Top URLS", top_urls_path %> |
<%= link_to "Top Referrers", top_referrers_path %>

<h1 class="page_title">Top 5 Referrers for the Top 10 URLs</h1>

<div class="container" ng-app="AnalyticsDemo" ng-controller="TopReferrers">

<ul class="navigation">
  <li ng-repeat="(date, data) in reports">
    <a href="#{{date}}">{{ date }}</a>
  </li>
</ul>

<div ng-repeat="(date, array) in reports">
  <a name="{{date}}"><h2 class="date">{{ date }}</h2></a>
  <a href="#top"><span class="back">Go back to top</span></a>
  <table>
    <tr>
      <th>URL</th>
      <th>VISITS</th>
      <th>REFERRERS</th>
    </tr>
    <tr ng-repeat="data in array">
      <td>{{ data.url }}</td>
      <td>{{ data.visits }}</td>
      <td>
        <div class="referrer" ng-repeat="ref in data.referrers">
          <div class="ref_url">{{ ref.url }}</div>
          <div class="ref_visits">{{ ref.visits }}</div>
        </div>
      </td>
    </tr>
  </table>
</div>

app/views/stats/top_urls.html.erb
<%= link_to "Top URLS", top_urls_path %> |
<%= link_to "Top Referrers", top_referrers_path %>

<h1 class="page_title">Number of Page Views Per URL</h1>

<div class="container" ng-app="AnalyticsDemo" ng-controller="TopUrls">

<ul class="navigation">
  <li ng-repeat="(date, data) in reports">
    <a href="#{{date}}">{{ date }}</a>
  </li>
</ul>

<div ng-repeat="(date, data) in reports">
  <a name="{{date}}"><h2 class="date">{{ date }}</h2></a>
  <table>
    <tr>
      <th>URL</th>
      <th>VISITS</th>
    </tr>
    <tbody>
      <tr ng-repeat="(id, record) in data">
        <td>{{ record.url }}</td>
        <td>{{ record.visits }}</td>
      </tr>
    </tbody>
  </table>
</div>